### ISSUE TITLE
DragonDoor crash server

### ISSUE THREAD

**Issue by pxsxs** [rickoff/Tes3mp-0.8.x#1]
DragonDoor crash server when try to open a door

`[2022-02-15 15:28:39] [ERR]: ./server/scripts/custom/DragonDoor.lua:80: attempt to index upvalue 'DoorData' (a nil value)
[2022-02-15 15:28:39] [ERR]: [Script]: Server crash from script error!
terminate called after throwing an instance of 'luabridge::LuaException'
  what():  ./server/scripts/custom/DragonDoor.lua:80: attempt to index upvalue 'DoorData' (a nil value)
./tes3mp-server: line 7: 18047 Aborted`

full log file:
https://paste.debian.net/1231043/

**Comment by rickoff** [comment]
did you add the DoorData.json file in your data/custom/DragonDoor folder ?

**Comment by pxsxs** [comment]
my bad, sorry bro, thanks! :smile:
