### ISSUE TITLE
Feature Request/Idea for VocalDiscord

### ISSUE THREAD

**Issue by MushiShirohime** [rickoff/Tes3mp-0.8.x#2]
Didn't know where to exactly shove this so I am just submitting it as an issue lmao

Basically VocalDiscord but using Mumble

That's really it...
This idea stems from the Mumble Link mod for Minecraft that enables locational VOIP to work in that.

**Comment by rickoff** [comment]
it exists, you should contact its creator so that he can update it for version 0.8
https://github.com/perfectcolors/openmw-tes3mp-mumble

**Comment by MushiShirohime** [comment]
Far as I can tell that is an entire TES3MP client and not actually a script

**Comment by rickoff** [comment]
yes indeed but I do not know Mumble and in my opinion if it was done like that it is that it is the best solution for an effective proxy chat.
