### ISSUE TITLE
VocalDiscord not working and crashes when I disconnect from chat

### ISSUE THREAD

**Issue by Mofker** [rickoff/Tes3mp-0.8.x#3]
Hello!

After updating VocalDiscord to 8.0 I can't seem to get it working on my server. Nothing happens when the bot is started and will crash when someone disconencts from chat with the following error:

Uncaught Error: ...rrowind/server/lib/luadiscord/deps/coro-channel.lua:62: ...ver/lib/luadiscord/deps/discordia/libs/utils/Emitter.lua:105: ...ervers\Morrowind\server\lib\luadiscord\BotVocal.lua:162: attempt to index local 'DiscordFile' (a nil value)
stack traceback:
        [C]: in function 'assert'
        ...rrowind/server/lib/luadiscord/deps/coro-channel.lua:62: in function 'onPlain'
        .../server/lib/luadiscord/deps/secure-socket/biowrap.lua:76: in function <.../server/lib/luadiscord/deps/secure-socket/biowrap.lua:61>
        [C]: in function 'run'
        [string "bundle:/init.lua"]:52: in function <[string "bundle:/init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:/init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function <[string "bundle:deps/require.lua"]:266>

**Comment by rickoff** [comment]
Did you follow the installation correctly? The file below is not there or is not in the right place, check it.
Save the file as userdiscord.json inside your server/data/custom/VocalDiscord folder.

**Comment by Mofker** [comment]
I've carefully followed the steps in the installation instructions. The userdiscord.json file is located in server\data\custom\VocalDiscord. I have even tried placing it directly in the custom folder without success.

I've even tried again with a clean build of the latest server files without any luck

**Comment by rickoff** [comment]
sorry for the late reply, did you solve your problem? if you need do not hesitate to come and ask directly on discord

**Comment by Mofker** [comment]
Hey there!
Sorry for also replying late. I haven't had more time to test it out. I
should be getting some time off to do some testing soon. I'll get back to
you!
